# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization

name: Dependabot

on:
  pull_request_target:
    branches:
      - main
      - master
      - stable*

permissions:
  contents: read

jobs:
  auto-approve-merge:
    runs-on: ubuntu-latest
    permissions:
      # for hmarr/auto-approve-action to approve PRs
      pull-requests: write 

    steps:
      # Github actions bot approve
      - uses: hmarr/auto-approve-action@v3
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Nextcloud bot approve and merge request
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        if: github.actor == 'dependabot[bot]'
        with:
          target: minor
          github-token: ${{ secrets.COOKBOOK_BOT_TOKEN }}
